--------------------------------------------------------
--  파일이 생성됨 - 월요일-7월-15-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOOKING_NO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ALPHA"."BOOKING_NO_SEQ"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_NO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ALPHA"."PAYMENT_NO_SEQ"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AMENITIES
--------------------------------------------------------

  CREATE TABLE "ALPHA"."AMENITIES" 
   (	"AMENITIES_CODE" VARCHAR2(50 BYTE), 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "ALPHA"."BOOKING" 
   (	"BOOKING_ID" VARCHAR2(50 BYTE), 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"STAY_PEOPLE" NUMBER(3,0), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"BOOKSTAT_CODE" VARCHAR2(50 BYTE), 
	"PAYSTAT_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOKING_ONEDAY_PRICE_MAP
--------------------------------------------------------

  CREATE TABLE "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" 
   (	"BOOKING_ID" VARCHAR2(50 BYTE), 
	"ONEDAY" DATE, 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"ONEDAY_PRICE" NUMBER(12,0), 
	"CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANCEL_REFUND
--------------------------------------------------------

  CREATE TABLE "ALPHA"."CANCEL_REFUND" 
   (	"BOOKING_ID" VARCHAR2(50 BYTE), 
	"PAYMENT_NO" NUMBER(5,0), 
	"REFUND_PRICE" NUMBER(12,0), 
	"CANCELREA_CODE" VARCHAR2(50 BYTE), 
	"CANCEL_CONTENT" VARCHAR2(4000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CODE
--------------------------------------------------------

  CREATE TABLE "ALPHA"."CODE" 
   (	"CODE_KEY" VARCHAR2(20 BYTE), 
	"GROUP_KEY" VARCHAR2(20 BYTE), 
	"CODE_NAME" VARCHAR2(30 BYTE), 
	"CODE_DESC" VARCHAR2(100 BYTE), 
	"USE_YN" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CODE_GROUP
--------------------------------------------------------

  CREATE TABLE "ALPHA"."CODE_GROUP" 
   (	"GROUP_KEY" VARCHAR2(20 BYTE), 
	"GROUP_NAME" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ONEDAY_PRICE
--------------------------------------------------------

  CREATE TABLE "ALPHA"."ONEDAY_PRICE" 
   (	"ONEDAY" DATE, 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"ONEDAY_PRICE" NUMBER(12,0), 
	"UPDATE_DATE" DATE DEFAULT sysdate, 
	"LEFE_PEOPLE" NUMBER(2,0), 
	"ONESTAT_CODE" VARCHAR2(50 BYTE) DEFAULT 'one01', 
	"CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "ALPHA"."PROFILE" 
   (	"PROITEM_CODE" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "ALPHA"."REVIEW" 
   (	"BOOKING_ID" VARCHAR2(50 BYTE), 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"RATING" NUMBER(1,0), 
	"REVIEW_CONTENT" VARCHAR2(4000 BYTE), 
	"REVIEW_IMAGE" VARCHAR2(4000 BYTE), 
	"ORIGINAL_NAME" VARCHAR2(4000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

  CREATE TABLE "ALPHA"."ROOM" 
   (	"ROOM_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"ROOM_NAME" VARCHAR2(50 BYTE), 
	"ROOMTYPE_CODE" VARCHAR2(50 BYTE), 
	"ROOMCATE_CODE" VARCHAR2(50 BYTE), 
	"DEFAULT_PRICE" NUMBER(12,0), 
	"START_DATE" DATE DEFAULT NULL, 
	"END_DATE" DATE DEFAULT NULL, 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"ROOMSTAT_CODE" VARCHAR2(50 BYTE) DEFAULT 'rst01', 
	"ROOM_CONTENT" VARCHAR2(4000 BYTE), 
	"REJECT_CONTENT" VARCHAR2(2000 BYTE), 
	"MAX_PEOPLE" NUMBER(2,0), 
	"TOTAL_SPACE" NUMBER(3,0), 
	"TOTAL_BED" NUMBER(3,0), 
	"TOTAL_BATH" NUMBER(3,0), 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"UPDATE_DATE" DATE DEFAULT sysdate, 
	"MAIN_IMAGE" VARCHAR2(200 BYTE), 
	"ORIGINAL_NAME" VARCHAR2(50 BYTE), 
	"BANK_CODE" VARCHAR2(50 BYTE), 
	"ACCOUNT_NO" VARCHAR2(50 BYTE), 
	"VIEWS" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROOM_IMAGE
--------------------------------------------------------

  CREATE TABLE "ALPHA"."ROOM_IMAGE" 
   (	"IMAGE_NO" NUMBER(5,0), 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"IMAGE" VARCHAR2(200 BYTE), 
	"ORIGINAL_NAME" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROOM_PAYMENT
--------------------------------------------------------

  CREATE TABLE "ALPHA"."ROOM_PAYMENT" 
   (	"PAYMENT_NO" NUMBER(5,0), 
	"BOOKING_ID" VARCHAR2(50 BYTE), 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"PAYTYPE_CODE" VARCHAR2(50 BYTE), 
	"CARD_NO" VARCHAR2(50 BYTE), 
	"REFUND_ACCOUNT" VARCHAR2(50 BYTE), 
	"PAYMENT_PRICE" NUMBER(12,0), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROOM_REPORT
--------------------------------------------------------

  CREATE TABLE "ALPHA"."ROOM_REPORT" 
   (	"BOOKING_ID" VARCHAR2(50 BYTE), 
	"ROOM_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"ROOMRPCT_CODE" VARCHAR2(50 BYTE), 
	"REPORT_CONTENT" VARCHAR2(4000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ALPHA"."USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_PW" VARCHAR2(50 BYTE), 
	"USER_BIRTH" DATE, 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"USER_PHONE" VARCHAR2(50 BYTE), 
	"USERSTAT_CODE" VARCHAR2(50 BYTE) DEFAULT 'ust01', 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"USERAUTH_CODE" VARCHAR2(50 BYTE) DEFAULT 'usa01', 
	"USER_IMAGE" VARCHAR2(100 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_AUTH_NO
--------------------------------------------------------

  CREATE TABLE "ALPHA"."USER_AUTH_NO" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"AUTH_NO" VARCHAR2(6 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WISHLIST
--------------------------------------------------------

  CREATE TABLE "ALPHA"."WISHLIST" 
   (	"ROOM_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ALPHA.AMENITIES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_PROFILE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."PK_PROFILE" ON "ALPHA"."PROFILE" ("PROITEM_CODE", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ROOM_IMAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."PK_ROOM_IMAGE" ON "ALPHA"."ROOM_IMAGE" ("IMAGE_NO", "ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."REVIEW_PK" ON "ALPHA"."REVIEW" ("BOOKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index WISHLIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."WISHLIST_PK" ON "ALPHA"."WISHLIST" ("ROOM_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_AUTH_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."USER_AUTH_NO_PK" ON "ALPHA"."USER_AUTH_NO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROOM_REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."ROOM_REPORT_PK" ON "ALPHA"."ROOM_REPORT" ("BOOKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CANCEL_REFUND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."CANCEL_REFUND_PK" ON "ALPHA"."CANCEL_REFUND" ("BOOKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ONEDAY_PRICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."PK_ONEDAY_PRICE" ON "ALPHA"."ONEDAY_PRICE" ("ONEDAY", "ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOOKING_ONEDAY_PRICE_MAP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."BOOKING_ONEDAY_PRICE_MAP_PK" ON "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" ("ONEDAY", "ROOM_ID", "BOOKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROOM_PAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."ROOM_PAYMENT_PK" ON "ALPHA"."ROOM_PAYMENT" ("PAYMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_BOOKING
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."PK_BOOKING" ON "ALPHA"."BOOKING" ("BOOKING_ID", "ROOM_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_AMENITIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALPHA"."PK_AMENITIES" ON "ALPHA"."AMENITIES" ("AMENITIES_CODE", "ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CODE_GROUP
--------------------------------------------------------

  ALTER TABLE "ALPHA"."CODE_GROUP" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CODE_GROUP" ADD PRIMARY KEY ("GROUP_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."CODE_GROUP" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOM_REPORT
--------------------------------------------------------

  ALTER TABLE "ALPHA"."ROOM_REPORT" ADD CONSTRAINT "ROOM_REPORT_PK" PRIMARY KEY ("BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."ROOM_REPORT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_REPORT" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_REPORT" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_REPORT" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_REPORT" MODIFY ("ROOMRPCT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ONEDAY_PRICE
--------------------------------------------------------

  ALTER TABLE "ALPHA"."ONEDAY_PRICE" ADD CONSTRAINT "PK_ONEDAY_PRICE" PRIMARY KEY ("ONEDAY", "ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."ONEDAY_PRICE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ONEDAY_PRICE" MODIFY ("ONESTAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ONEDAY_PRICE" MODIFY ("LEFE_PEOPLE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ONEDAY_PRICE" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ONEDAY_PRICE" MODIFY ("ONEDAY_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ONEDAY_PRICE" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ONEDAY_PRICE" MODIFY ("ONEDAY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANCEL_REFUND
--------------------------------------------------------

  ALTER TABLE "ALPHA"."CANCEL_REFUND" ADD CONSTRAINT "CANCEL_REFUND_PK" PRIMARY KEY ("BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."CANCEL_REFUND" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CANCEL_REFUND" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CANCEL_REFUND" MODIFY ("CANCELREA_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CANCEL_REFUND" MODIFY ("REFUND_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CANCEL_REFUND" MODIFY ("PAYMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "ALPHA"."ROOM" ADD PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."ROOM" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM" MODIFY ("ROOM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOKING_ONEDAY_PRICE_MAP
--------------------------------------------------------

  ALTER TABLE "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" ADD CONSTRAINT "BOOKING_ONEDAY_PRICE_MAP_PK" PRIMARY KEY ("ONEDAY", "ROOM_ID", "BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" MODIFY ("ONEDAY_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" MODIFY ("ONEDAY" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING_ONEDAY_PRICE_MAP" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "ALPHA"."PROFILE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."PROFILE" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY ("PROITEM_CODE", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."PROFILE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."PROFILE" MODIFY ("PROITEM_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."PROFILE" MODIFY ("CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WISHLIST
--------------------------------------------------------

  ALTER TABLE "ALPHA"."WISHLIST" ADD CONSTRAINT "WISHLIST_PK" PRIMARY KEY ("ROOM_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."WISHLIST" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."WISHLIST" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."WISHLIST" MODIFY ("ROOM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "ALPHA"."BOOKING" ADD CONSTRAINT "BOOKING_PK" PRIMARY KEY ("ROOM_ID", "USER_ID", "BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."BOOKING" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING" MODIFY ("BOOKSTAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING" MODIFY ("PAYSTAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING" MODIFY ("STAY_PEOPLE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."BOOKING" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AMENITIES
--------------------------------------------------------

  ALTER TABLE "ALPHA"."AMENITIES" ADD CONSTRAINT "PK_AMENITIES" PRIMARY KEY ("AMENITIES_CODE", "ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."AMENITIES" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."AMENITIES" MODIFY ("ROOM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CODE
--------------------------------------------------------

  ALTER TABLE "ALPHA"."CODE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CODE" MODIFY ("GROUP_KEY" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CODE" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."CODE" ADD PRIMARY KEY ("CODE_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."CODE" MODIFY ("CODE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOM_IMAGE
--------------------------------------------------------

  ALTER TABLE "ALPHA"."ROOM_IMAGE" ADD CONSTRAINT "PK_ROOM_IMAGE" PRIMARY KEY ("IMAGE_NO", "ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."ROOM_IMAGE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_IMAGE" MODIFY ("ORIGINAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_IMAGE" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_IMAGE" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_IMAGE" MODIFY ("IMAGE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOM_PAYMENT
--------------------------------------------------------

  ALTER TABLE "ALPHA"."ROOM_PAYMENT" ADD CONSTRAINT "ROOM_PAYMENT_PK" PRIMARY KEY ("PAYMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."ROOM_PAYMENT" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_PAYMENT" MODIFY ("PAYMENT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_PAYMENT" MODIFY ("PAYTYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_PAYMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_PAYMENT" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_PAYMENT" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."ROOM_PAYMENT" MODIFY ("PAYMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_AUTH_NO
--------------------------------------------------------

  ALTER TABLE "ALPHA"."USER_AUTH_NO" ADD CONSTRAINT "USER_AUTH_NO_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."USER_AUTH_NO" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USER_AUTH_NO" MODIFY ("AUTH_NO" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USER_AUTH_NO" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ALPHA"."USERS" MODIFY ("USERAUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USERS" MODIFY ("USERSTAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."USERS" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USERS" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USERS" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USERS" MODIFY ("USER_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."USERS" MODIFY ("USER_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "ALPHA"."REVIEW" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."REVIEW" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."REVIEW" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."REVIEW" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALPHA"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ALPHA"."REVIEW" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CODE
--------------------------------------------------------

  ALTER TABLE "ALPHA"."CODE" ADD CONSTRAINT "FK_CODE_GROUP" FOREIGN KEY ("GROUP_KEY")
	  REFERENCES "ALPHA"."CODE_GROUP" ("GROUP_KEY") ENABLE;
